version: "3"

services:
    payment-service:
        image: webdevops/php:8.1
        ports:
            - 8083:8080
        working_dir: /app
        environment: 
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_MEMORY_LIMIT=2048M
            - PHP_MAX_EXECUTION_TIME=300
            - PHP_POST_MAX_SIZE=2048M
            - PHP_UPLOAD_MAX_FILESIZE=2048M
        volumes:
            - './app:/app'
        #deploy:
            #resources:
                #limits:
                    #cpus: '0.25'
                    #memory: 1024M
        command: >
            bash -c "./rr serve"
    payment_DB:
        image: postgres:11.12
        environment:
            POSTGRES_DB: payment
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - payment-db-data:/var/lib/postgresql/data/
        ports:
            - "8330:5432"
        command: ["postgres", "-c", "logging_collector=on", "-c", "log_destination=stderr", "-c", "max_connections=50000"]

    payment_test_DB:
        image: postgres:11.12
        environment:
            POSTGRES_DB: payment
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - payment-test-db-data:/var/lib/postgresql/data/
        ports:
            - "8331:5432"
        command: ["postgres", "-c", "logging_collector=on", "-c", "log_destination=stderr", "-c", "max_connections=50000"]

volumes:
    payment-db-data:
    payment-test-db-data: